version: "3.8"

networks:
  app-network:
    driver: bridge

services:
  app:
    container_name: mynews
    image: mynews
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - /app/node_modules